language: ruby
rvm:
  - 2.2.4

before_script:
  - psql -U postgres -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate

services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 71b5f223ea4eb952d4f406fd391edbde058384fa7c156ac024955c4c61a4fdc5
