# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f313529443cb3abd1f7aec0e84c98c98648d33afc8cc3278412a9f3903beb77348fa467958d323fa19b750bec16ba5b16bd98c8df56b1b3617b1a533d1b207

test:
  secret_key_base: cf13c7dab3e1363b9fac927741e8420cd14c95e30e60b0004a4c415f2ba6ae767e14f5ea0231ad8f2467b17627803dd86833e651f7bb27ed1f168889047e105b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
